### ISSUE TITLE
[RUP] Software Requirements Specification

### ISSUE THREAD

**Issue by tsvetan-ganev** [uni-ruse-software-engineering-2017/itt-exam-registration-system#5]
Create the Software Requirements Specification document. You should use the functional requirements from the `e1/Requirements.xls` file.

The most important bullet point is `3.1. Functionality` - you have to specify all of the major functionalities that our system will have to offer as sub-list bullet points, e.g. `3.1.1. Student registration`, `3.1.2. Professor registration`, etc. 

RUP template name: `Software-Requirements-Specification-rup_srs.dot`

**Comment by xTrEeMx** [comment]
I'm ready. Uploaded in Google Drive.
